### ISSUE TITLE
Zbscapy - Book or video?

### ISSUE THREAD

**Issue by Krostas** [riverloopsec/killerbee#100]
Hi,

Can anyone suggest some video or book that it will be good to urdestand how zbscapy works?
If possible something specific for ZigBee.

Thanks

**Comment by rmspeers** [comment]
zbscapy is a script that is pretty short itself, but gives you a large amount of power. It drops you into a Scapy shell with a KillerBee instance available to you. This allows you to use a set of functions in scapy_extensions.py to send and receive packets, that are parsed or constructed using Scapy (scapy-com to be specific). I suggest you read up on Scapy in general, there is no additional documentation other than a presentation I gave about doing IEEE 802.15.4 in Scapy at ShmooCon 2011, but that touched on it very briefly.
