### ISSUE TITLE
Zbsniff can't find key on pcap with Transport Key

### ISSUE THREAD

**Issue by Krostas** [riverloopsec/killerbee#101]
Hi,

I have a pcap file with the TRANSPORT KEY inside. I can see it in wireshark but when I use zbsniff I can't get any result.

In wireshark I needed to confgure with the Home Automation Profile Key. Is there any way to configure zbsniff to use this key?

Is this is not the problem, why can't zbsniff find the Transport Key?
Thanks

**Comment by wveilleux** [comment]
Hi Krostas, any feedback on this issue ? I have the same problem. Thx, Regards
