### ISSUE TITLE
Zbreplay is not working

### ISSUE THREAD

**Issue by Krish2402** [riverloopsec/killerbee#106]
Hello ,

I am not able to run zbreplay using the Attify GUI wrapper. 

this is the error I am getting
  File "main.py", line 138, in zbreplay
    file=self.zbreplayFile.text()
AttributeError: 'QComboBox' object has no attribute 'text'

**Comment by rmspeers** [comment]
@Krish2402 This is not an issue in KillerBee, but instead in a third-party GUI wrapper. Please contact that project for assistance.
