### ISSUE TITLE
pcap timestamp is not correct. time.time() returns just 1/100sec

### ISSUE THREAD

**Issue by volkerrichert** [riverloopsec/killerbee#112]
https://github.com/riverloopsec/killerbee/blob/987d3bf30866b73f46d39fac7706af71fdb3c975/killerbee/pcapdump.py#L229-L233

`        if ts_sec == None or ts_usec == None:
            dt = datetime.now()
            ts_sec = int(dt.strftime('%s'))
            ts_usec = dt.microsecond
`
has a better resolution.

also add 
`from datetime import datetime`

Volker

P..s: just by hand so, no PR or diff

**Comment by rmspeers** [comment]
change merged, thanks for find, fix, and PR!
