### ISSUE TITLE
Can i flash killerbee on raspbee ? 

### ISSUE THREAD

**Issue by marcogaudino** [riverloopsec/killerbee#115]
Hi guys, 

i would like to know if i can flashing the Killerbee firmware on Raspbee. Can someone help me?

Thank you very much. 

Marco

**Comment by riverloopsec** [comment]
We do not have firmware designed for that device. You can add support via a
device driver module to the framework.

**Comment by rmspeers** [comment]
@marcogaudino  did that answer your question or do you have other questions?

**Comment by rmspeers** [comment]
@marcogaudino do you have any outstanding questions? Are you working on adding this support?

**Comment by marcogaudino** [comment]
No no! I don’t have any question! I have finished my work.

Il giorno mer 7 nov 2018 alle 14:10 Ryan Speers <notifications@github.com>
ha scritto:
