### ISSUE TITLE
GPS not working in ZBWarDrive

### ISSUE THREAD

**Issue by bushido8989** [riverloopsec/killerbee#120]
Howdy!

Platform is a Nexus 5 running Kali Nethunter, GPSD running and verified (using cgps and testgps.py) with satellite fix.

Everything else in the framework appears to work fine. Can dump packets; zbstumbler works fine. 

Installed via cloning the repo. Error returned when using the "-g -v" flags:

------

WARNING: No route found for IPv6 destination :: (no default route?)
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-armv7l/egg/killerbee/zbwardrive/zbwardrive.py", line 21, in gpsdPoller
    gpsd = gps.gps()
AttributeError: 'module' object has no attribute 'gps'
Warning: You are using pyUSB 1.x, support is in beta.

---

Any assistance would be great!!

**Comment by rmspeers** [comment]
This appears as the gps module doesn't have a function called gps. That is odd as it looks like that function exists. If you used `https://github.com/riverloopsec/killerbee/blob/master/killerbee/zbwardrive/testGPS.py` to test, then that is doing the same call, however as you will see there. Please ensure you are testing with that file and also note the directory you are running each command from -- my guess is it's something like that.

**Comment by taylorcenters** [comment]
Closing inactive. Please check out the latest version that has updated to Python3. Open a new issue if you still run into problems! thanks!
