### ISSUE TITLE
please tag 2.0 release

### ISSUE THREAD

**Issue by blshkv** [riverloopsec/killerbee#128]
It was announced on the website, however it is not available for download.
Please release a proper tar.gz file.

**Comment by rmspeers** [comment]
Unless there is a specific need for the 2.0 in a tar.gz, perhaps it's best if we just do this for the upcoming 2.7 once it is merged down.
May I ask what the tar.gz is needed for as typically the install for most users is a git clone and then a setup.py based install. Is it for packaging into a distro or similar?

**Comment by blshkv** [comment]
You are right, it is useful for all distro to pickup the latest version. I'm Pentoo developer and pushed the latest snaphost here:
https://github.com/pentoo/pentoo-overlay/tree/master/net-wireless/killerbee

However, other distros are still on the version 1.0, see:
https://repology.org/metapackage/killerbee/versions

**Comment by blshkv** [comment]
just a little "thanks" would be nice before closing the bug

**Comment by taylorcenters** [comment]
Sorry - I went on autopilot while trying to clean up the project. Thanks for your help on this one!
