### ISSUE TITLE
Discontinuation of RZUSB Stick

### ISSUE THREAD

**Issue by joswr1ght** [riverloopsec/killerbee#140]
A friend sent me a link to the discontinuation notice for the RZUSB stick:

https://www.mouser.com/ProductDetail/Microchip-Technology-Atmel/ATAVRRZUSBSTICK?qs=txwRF2uft8wSedIxfUdhAA%3D%3D

Thoughts on alternative, inexpensive hardware?

**Comment by rmspeers** [comment]
I'm thinking the CC2531 dev boards are probably good to be using more often now -- similar form factor, price, and such. We have basic support for those in now.

**Comment by rmspeers** [comment]
We also now have support for many of the Ember sticks. Closing this but feel free to reopen as needed.

**Comment by yesimxev** [comment]
@rmspeers - just to make sure I would select the correct one, Cortet EM358 USB Stick would work? I wanted to buy RZUSB too and didn't find anything under 100$

**Comment by rmspeers** [comment]
I haven't had an opportunity to evaluate that specific device so I can't confirm that. I have had good success with the CC2531 EMK for RX mode operations - and with effort one should be able to add TX to that as well.

**Comment by yesimxev** [comment]
Which ember sticks/chips do you support recently? Just looking for one which would work for TX
