### ISSUE TITLE
KillerBee doesn't know how to interact with serial device at '/dev/ttyUSB0'

### ISSUE THREAD

**Issue by cn0xroot** [riverloopsec/killerbee#157]
./zbwireshark -c 15

```
See the GoodFET FAQ about missing info flash.
Traceback (most recent call last):
  File "./zbwireshark", line 108, in <module>
    main()
  File "./zbwireshark", line 61, in main
    with KillerBee(device=args.devstring) as kb:
  File "/usr/local/lib/python2.7/dist-packages/killerbee-2.7.0-py2.7-linux-x86_64.egg/killerbee/__init__.py", line 167, in __init__
    raise KBInterfaceError("KillerBee doesn't know how to interact with serial device at '%s'." % self.dev)
killerbee.kbutils.KBInterfaceError: KillerBee doesn't know how to interact with serial device at '/dev/ttyUSB0'
```

system:ubuntu 12.04
devices:api-mote

**Comment by cn0xroot** [comment]
sudo ./zbid 
           Dev Product String       Serial Number

See the GoodFET FAQ about missing info flash.

**Comment by alphaomicron** [comment]
Is your device recognized by the host at all? have the same issue with zbid

**Comment by rmspeers** [comment]
@cn0xroot  this should be working on Ubuntu 12.04 as you indicate, I suggest doing a single reflash of the device (make sure to use the appropriate goodfet.bsl options, either erase and then program and then verify, or program and verify (providing the same file as you're flashing as the password if you get that message).

**Comment by rmspeers** [comment]
Is this now fixed? This looks like the OS didn't have the USB connected -- perhaps a VM without it attached or a bad cable, etc?

**Comment by cn0xroot** [comment]
still unstable（not 100% work）, only  30% -50% ,Already give up to use apimote
