### ISSUE TITLE
KB FW Source

### ISSUE THREAD

**Issue by GoogleCodeExporter** [riverloopsec/killerbee#16]
```
Greetings,

Where can I DL the KB FW source?

Thanks,
Komp


```

Original issue reported on code.google.com by `komp...@gmail.com` on 20 Nov 2012 at 6:12

**Comment by joswr1ght** [comment]
Added the RZUSBSTICK firmware source.  It wasn't anything complicated with licensing, I just couldn't find it after transitioning laptops a few years ago.
