### ISSUE TITLE
zbid output on APImote v4

### ISSUE THREAD

**Issue by alphaomicron** [riverloopsec/killerbee#163]
OS: debian, ubuntu
Device: APImote v4 beta

While giving command zbid The output is

           Dev Product String       Serial Number
  /dev/ttyUSB0 GoodFET Api-Mote v2            

Is this correct? I thought it should give v4

**Comment by fhred** [comment]
I'm not 100% sure, but I think the `v2` there relates to the firmware version. Read it like: 

GoodFET for Api-Mote version 2

**Comment by alphaomicron** [comment]
Thank you.

**Comment by rmspeers** [comment]
Output of v2 for zbid is expected, although perhaps a better output would be "v2+". Basically v1 and v2-v4 have to be enumerated differently and communicated with differently, so that's all it's saying. v2, 3, and 4 are all communicated with the same way.

**Comment by alphaomicron** [comment]
So does this mean I have to flash a newer firmware?

**Comment by rmspeers** [comment]
No, these devices are shipped with up-to-date firmware and only should need reflashing if you have updated the firmware and want to add features/etc.

**Comment by rmspeers** [comment]
Closing. New FAQ will also remind people of this.
