### ISSUE TITLE
Add tshark support for headless sniffing support

### ISSUE THREAD

**Issue by twistedvip** [riverloopsec/killerbee#178]
This solution is very valuable for some zigbee testing on a Linux machine, however, I see zbwireshark currently is hard-coded to use wireshark which makes this unable to work when wanting to run automated headless testing (say through Jenkins).

From initial tests, it looks like it should be an easy modification of zbwireshark of simply modifying the start_wireshark() function changing 'wireshark' to 'tshark', removing '-k' argument, and adding an output file argument, giving the location to tshark with the '-w' argument.

A possible solution could simply be a new tool called 'zbtshark'.

**Comment by rmspeers** [comment]
Sure,  do you have a PR you’d like to submit for this? If not, I will keep this ticket open as an idea to get to in an upcoming release.

**Comment by twistedvip** [comment]
Hey sorry took so long to respond. I don't have a PR open yet, but I sure can create one real quick! Thanks for such a quick response to this request though

**Comment by twistedvip** [comment]
@rmspeers Actually trying to create my own branch, I'm not sure I have permissions to do so and create a pull request. I'll just attach the zbtshark file here. I haven't really done much testing, just wanted to give the general idea for you. (Had to zip the file up since github only supports a limited amount of file formats.

[zbtshark.zip](https://github.com/riverloopsec/killerbee/files/3541264/zbtshark.zip)

**Comment by taylorcenters** [comment]
hi, you'll need to fork the repo and create the branch and changes you want, then you can open a PR from that fork back into this repo. From there we will be able to work with you while reviewing the PR
