### ISSUE TITLE
"Received frame is not a beacon (FCF=4188)" error with zbstumbler

### ISSUE THREAD

**Issue by sandwich-destroyer** [riverloopsec/killerbee#181]
When trying to discover ZigBee networks I am getting the above error for known networks. I Have the API-Mote and antenna right next to the Zigbee module and the door lock that I am testing. I am not sure how to troubleshoot this.

**Comment by sandwich-destroyer** [comment]
Example output:
```
root@kali:/opt/killerbee/tools# python zbstumbler -c 25 -w /root/zbstumbler_ch25.csv -v
zbstumbler: Transmitting and receiving on interface '/dev/ttyUSB1'
Transmitting beacon request.
Transmitting beacon request.
Received frame.
Received frame is not a beacon (FCF=4188).
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
Received frame.
Received frame is not a beacon (FCF=4188).
Transmitting beacon request.
Transmitting beacon request.
Transmitting beacon request.
```

**Comment by rmspeers** [comment]
I suggest looking at the packets coming back and understanding if they are either not a standard beacon that it is coded to expect, or if there is packet corruption, or what. You may be saturating your radio frontend and may need a little distance or something.

**Comment by SteveJM** [comment]
I see these a lot in "noisy" environments. I've always believed that they are due to signal noise being received and accidentally processed, or other RF stomping on the packet making it unintelligible.

**Comment by rmspeers** [comment]
Yes, for whatever reason causes it at the RF layer -- collision, saturation, etc -- it is basically bit flips at the RF layer causing issues from what I can tell. Space, isolation, etc should be the fixes.
