### ISSUE TITLE
zbdsniff parsing error

### ISSUE THREAD

**Issue by whoot** [riverloopsec/killerbee#186]
Hi,

I´m trying to transform everything from python2 to python3 and having a bad time here and there :D 
Maybe you can help me. When executing zbdsniff as follows with python2 everything works:
```
zbdsniff -f ../sample/control4-sample.pcap -k 21323232

Processing ../sample/control4-sample.pcap
[+] Processed 1 capture files.
```

However, doing it with python3, gives me the following error:
```
python3 zbdsniff -f ../sample/control4-sample.pcap -k 21323232

Processing ../sample/control4-sample.pcap
Traceback (most recent call last):
  File "zbdsniff", line 111, in <module>
    sniffNetworkKey(pkts, options.transportKey, options.verbose)
  File "zbdsniff", line 34, in sniffNetworkKey
    keyHash = sec_key_hash(key, '\0')
TypeError: argument 2 must be a byte string of length 1, not str
```

I dont find anything on the internet or on any other killerbee script about the 'sec_key_hash' function. What does it do? And how can I transform it to python3?

Thanks for your help!

**Comment by hgbstu** [comment]
In Zigbee different keys are derived from a Link Key (the key argument of the sec_key_hash function is a Link Key) for different purposes, in this specific case a so called Key-Transport Key is derived. This Key-Transport Key is used for protecting the over the air Network Key transport.

Probably this should work for you
`keyHash= sec_key_hash(key, struct.pack("B", 0x00))`

**Comment by whoot** [comment]
Thanks for your help, but this doesnt work. Now i´m getting the following error:
```
Processing ../sample/control4-sample.pcap
Traceback (most recent call last):
  File "zbdsniff", line 111, in <module>
    sniffNetworkKey(pkts, options.transportKey, options.verbose)
  File "zbdsniff", line 34, in sniffNetworkKey
    keyHash = sec_key_hash(key, struct.pack('B', 0x00))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 1: invalid continuation byte
```

**Comment by whoot** [comment]
seems like they 'key' value is producing the error.
Any ideas?

**Comment by SteveJM** [comment]
Should be fixed in the Python3 PR (I've run a very similar command, and it was that sort of issue that I had to address in the branch).

**Comment by whoot** [comment]
thanks! added it to the sewio pr
