### ISSUE TITLE
Atmel AVR Wireless Services AVR2017_RZRAVEN_Firmware.zip

### ISSUE THREAD

**Issue by 971106029** [riverloopsec/killerbee#191]
This file link is now invalid. Can you give me a download link that you have?

**Comment by taylorcenters** [comment]
@rmspeers do you have a link to this firmware?

**Comment by rmspeers** [comment]
A quick google seems to point to someone hosting it on their personal site at https://www.avrfreaks.net/forum/avr2017-firmware - no idea if it is good/etc.

**Comment by taylorcenters** [comment]
thanks - try at your own risk
