### ISSUE TITLE
TelosB - AttributeError: 'Serial' has no attribute 'setBaudrate'

### ISSUE THREAD

**Issue by Lithimlin** [riverloopsec/killerbee#193]
I've tried to flash killerbee using the `./flash_telosb.sh` and run into a couple of problems:

* The `goodfet.bsl` assumes that I have python2 set as my default. I changed the first line to call python2 instead of just python
* After having done that, I got the error mentioned in the title. Maybe I have the wrong `serial` library installed?

I'll open another issue to mention the following again but it would be really helpful if there was a virtualenv to open with the needed libraries with their correct versions installed and to switch from python2 to python3 since the support will run out soon.

That being said, how do I solve the AttributeError?

**Comment by Lithimlin** [comment]
Due to a recent change of PySerial, `self.serialport.setBaudrate(baudrate)` in `goodfet.bsl`, line 1392 now needs to be `self.serialport.baudrate = baudrate`

**Comment by taylorcenters** [comment]
Thanks, PR #252 made this change!
