### ISSUE TITLE
Python2 and virtualenv usage

### ISSUE THREAD

**Issue by Lithimlin** [riverloopsec/killerbee#194]
while trying to install killerbee I ran into a few issues with my python version, library versions and dependencies. This would be easily fixed by including a virtual environment in this repository with the correct python and library versions.

Switching to python3 would also be good since the support for python2 will run out soon.

**Comment by rmspeers** [comment]
For Python 3, please see https://github.com/riverloopsec/killerbee/pull/204 and try that branch and see if that helps. Please leave comments in that PR.

**Comment by taylorcenters** [comment]
Closed - please reopen if you still have issues on python3 with the most recent version of kb
