### ISSUE TITLE
Killerbee - RZUSBSTICK - ZBstumbler and some other commands not functioning - Raspberry Pi 3 B+ - Kali-64bit

### ISSUE THREAD

**Issue by JoeAJLaw** [riverloopsec/killerbee#203]
Hey all, 

I am working on a university project to do with IoT devices, and wanted to use Killerbee in my project. However, upon receiving the RZUSBSTICK which is flashed with Killerbee which I have checked through forums and the "ZBID" command, but some commands are not appropriately functioning.  Below are some examples of the issue:

![image](https://user-images.githubusercontent.com/22789766/75026892-9ed76d00-5495-11ea-8edf-8903e05782f2.png)

![image](https://user-images.githubusercontent.com/22789766/75027031-d5ad8300-5495-11ea-9ddf-deff07502de4.png)

Or if it does work on a channel e.g. 14 it will receive frames and then eventually die.
![image](https://user-images.githubusercontent.com/22789766/75027799-12c64500-5497-11ea-852e-9a1c808b225f.png)

The weirdest thing is that sometimes it will find a channel e.g. 22 and then when trying to scan that channel directly it will say it doesn't exist. 

![image](https://user-images.githubusercontent.com/22789766/75027908-3a1d1200-5497-11ea-8bbf-cba5f3d3d5c5.png)

Has anyone else experienced this? Or can provide a step-by-step solution of what needs to be done? 

I am using a Raspberry Pi 3 B+ with Kali Linux 64-bit

**Comment by rmspeers** [comment]
I have not seen that behavior, but although Pi3 w/ Kali 64 should work, it may be the platform

Also please confirm your Killerbee version that you installed from scratch, not using what comes on Kali.

**Comment by rmspeers** [comment]
Please let me know if you have this issue anymore or can provide the above info.

**Comment by grf240** [comment]
I am having a similar issue to @JoeAJLaw with using the some of the commands. I receive "Exception: Error: Semantical Error".

**Comment by taylorcenters** [comment]
Hi please try again on the latest software as we've upgraded to Python3 and performed a lot of maintenance since this issue was last active.

**Comment by taylorcenters** [comment]
Closing inactive - please feel free to reopen this or create a new issue if this persists with the latest software!
