### ISSUE TITLE
Missing dependancy in Ubuntu 20.04 (Focal Fossa)

### ISSUE THREAD

**Issue by yg-ht** [riverloopsec/killerbee#206]
Ubuntu 20.04 does not have a python-gtk2 package so this needs to be replaced (possibly inline with this repo's Python3 dev?).

Someone has created a ppa to provide it, but that means trusting someones personal repo:

[https://launchpad.net/~nrbrtx/+archive/ubuntu/python2-stuff](https://launchpad.net/~nrbrtx/+archive/ubuntu/python2-stuff)

I'm afraid I neither have the time or the skill to work this one through and I suspect more than anything else it probably signifies the end of support for Python2.

**Comment by taylorcenters** [comment]
I will move zbfind ( the tool which is the sole dependency on gtk) to a new repo for posterity. This should remove the dependency.

**Comment by taylorcenters** [comment]
you should be able to use now on current develop branch on Python3 without gtk/cairo dependencies. Please reopen if still having issues. Thanks
