### ISSUE TITLE
Issue running commands - RZUSB USB Semantical Error

### ISSUE THREAD

**Issue by grf240** [riverloopsec/killerbee#208]
![20200625_170953](https://user-images.githubusercontent.com/67398124/85795793-dd608b00-b706-11ea-9f5a-bae2653bf747.jpg)

Installed all dependencies, Scapy and KillerBee, as well as having the RZUSB Stick Flashed with the KillerBee firmware, but cannot utilize. I am running a USB persistence Kali Linux and using "root" to run. ZBID works just fine and recognizes the RZUSB Stick. 

Can I get some advice as to where I might be going wrong or if there is an issue with the code?

Thanks!

**Comment by rmspeers** [comment]
Yes, and zbstumbler is also recognizing it's a RZUSBstick fine. It is some issue with the USB stack.

Try either going to pyUSB 0.x branch, or else  will need to be diagnosed further on the USB item. This appears to be an issue that a number of users face on newer USB stacks. I expect there is something where calls to pyUSB need to be updated or something?

You could also try taking the snippet of code that fails and reporting it to pyUSB to see if they have any ideas or have seen this?

**Comment by grf240** [comment]
@rmspeers Thank you for your advice. I attempted to install and run with an older version of pyUSB and wasn't successful. Additionally, I reached out the pyUSB github repo and they directed me back to RZUSB/KillerBee project repo. I wonder if any new releases to address this bug will be added soon.

**Comment by taylorcenters** [comment]
Please try with the latest software. Thanks!

**Comment by taylorcenters** [comment]
Closing inactive - please feel free to reopen this or create a new issue if this persists with the latest software!

**Comment by Crypt0s** [comment]
For what it's worth, adding a .1 second sleep after opening the RZUSBSTICK device for inject `kb.inject()` will make this error go away on the RZUSBSTICK -- I suspect that the microcontroller needs more time to react to the request.

**Comment by comeete** [comment]
Hi,Excuse-me but, Crypt0s, can you explain in more details how and where in the code can we add this time please. Thanks a lot!

**Comment by comeete** [comment]
Thanks Cryt0s, it works well !
