### ISSUE TITLE
How can I use zbdsniff to get network key？

### ISSUE THREAD

**Issue by BoxFighter** [riverloopsec/killerbee#211]
I see someone input`zbdsniff name.pcap` to get network key, then I use the same way , but I can not get the key.

And the example in /sample/control4-sample.pcap, it can not be loaded.

So I want to ask how to use killerbee to get the network key/transport key?

**Comment by BoxFighter** [comment]
Oh,I got it. zbdsniff can only find plaintext Transport key.
I solved my program by using default global trust center link key.

**Comment by rmspeers** [comment]
Yes, almost always on HA profiles and similar, the Global Trust Center Link Key from ZB HA 1.2 will be what you want to start with.
