### ISSUE TITLE
Is there any chance of support for a HackRF One?

### ISSUE THREAD

**Issue by Jab2870** [riverloopsec/killerbee#221]
Title covers it really, I have a HackRF One. Would it be possible to use this
with it?

https://greatscottgadgets.com/hackrf/one/

**Comment by rmspeers** [comment]
You'd need to write a dev_hackrf.py file that implements the functions (you can use another file as an example) and do that. Referencing https://github.com/riverloopsec/tumblerf/blob/develop/tumblerf/interfaces/interface_gr_ieee802_15_4.py may also be helpful to guide the implementation.

**Comment by taylorcenters** [comment]
No official plans to build the driver for the hackrf! But would be happy to review a PR if you ended up creating one!

**Comment by ep2277** [comment]
Ok, we will try it! 😄
