### ISSUE TITLE
Supported wifi adapter "alfa AWUS036NHR v2"

### ISSUE THREAD

**Issue by vukitoso** [riverloopsec/killerbee#222]
Hello.
Supported wifi adapter "alfa AWUS036NHR v2" - https://www.alfa.com.tw/products/awus036nhr?variant=36477538271304 ?

Chipset: Realtek RTL8188RU
Frequency Range: 2.412GHz ~ 2.483GHz

**Comment by rmspeers** [comment]
No, we do not support any WiFi (802.11) adapters to speak IEEE 802.15.4. Although I guess it’s possible the chip could be configured to speak 802.15.4, that would be an atypical configuration you’d have to figure out if it’s possible to put the chip’s PHY into, not to mention the MAC.

**Comment by riverloopsec** [comment]
Closing as no reply from user.
