### ISSUE TITLE
dot154decode imports an unexisting exception file and exception classes are..

### ISSUE THREAD

**Issue by Jegeva** [riverloopsec/killerbee#240]
not defined properly

raise UnsupportedPacket(
            raise BadKeyLength("Invalid key length (%d)." % len(key))
            raise BadPayloadLength(

**Comment by taylorcenters** [comment]
Thanks for reporting! I removed the unexisting import and created those exception classes in branch https://github.com/riverloopsec/killerbee/tree/bugfix/cc2531-assorted
