### ISSUE TITLE
unable to detect apimote on kali 

### ISSUE THREAD

**Issue by sailormoonnnnn** [riverloopsec/killerbee#257]
hi i am not sure how to get my apimote to display when i use zbid

<img width="651" alt="Screenshot 2022-06-02 at 10 56 52 AM" src="https://user-images.githubusercontent.com/86309098/171543460-6647a636-2914-431b-9be2-bd5fa8609616.png">

**Comment by Jungjungjungjung** [comment]
i am using kali linux on UTM
