### ISSUE TITLE
[Help required]

### ISSUE THREAD

**Issue by jbasement** [riverloopsec/killerbee#262]
Hello everyone,

this is not a technical issue but more a request for support/ help.
I was looking through the supported devices for KillerBee that also allow sending packages, like the ApiMote, Tmote sky or the Atmel RZ Raven USBSTICK. But none of those are available to purchase.
As I'm currently starting to write my bachelor thesis on this topic and I have to do some tests with KillerBee I wanted to ask for help where I could buy a support KillerBee device?
I'm just a regular student so I wont be able to build an ApiMote myself.

Thanks in advance

**Comment by jbasement** [comment]
Update:
I just found out, by sifting through old issues, that CC2531 devices are supported when using [BumbleBee firmware by virtualabs](https://github.com/virtualabs/cc2531-killerbee-fw). This wasn't listed on the firmware/readme.md. 
I can create a draft PR to update that readme but I think I'm missing the expertise to properly add the info there.

**Comment by declanCoster** [comment]
https://www.attify-store.com/products/apimote

**Comment by jbasement** [comment]
@declanCoster thanks for your reply. But at least for me it shows up as "Sold out".

**Comment by declanCoster** [comment]
Oh shoot, sorry didn't see that

**Comment by jbasement** [comment]
Created a PR for that https://github.com/riverloopsec/killerbee/pull/266
