### ISSUE TITLE
scapy-extensions.py requires scapy-com

### ISSUE THREAD

**Issue by GoogleCodeExporter** [riverloopsec/killerbee#27]
```
What steps will reproduce the problem?

Running zbscapy on a system without scapy-com will produce errors when trying 
to parse Dot15d4 layers of the ZigBee packets. 

=======================================
cutaway> zbscapy
In [1]: cap = kbrdpcap('/tmp/zb_test.pcap')
WARNING: PcapReader: unknown LL type [195]/[0xc3]. Using Raw packets
AttributeError  Traceback
---> cap = kbrdpcap('/tmp/zb_test.pcap')
/usr/local/lib/python2.7/dist-packages/killerbee-2.5.0-py2.7-linux-x86_64.egg/ki
llerbee/scapy_extensions.py
in kbrdpcap(filename, count, skip, nofcs)
   229    continue
   230  if nofcs: packet = Dot15d4(packet[1])
>>>231  else: packet = Dot15d4FCS(packet[1])
   224  lst.append(packet)
AttributeError: global name 'Dot15d4FCS' is not defined

In [2]:
=======================================

Therefore, scapy-com is a requirement to use scapy-extensions.py and should be 
listed as such. This could be tested using the following (which might require 
the loading of the sys module as well) after all of the imports:

=======================================
try:
    scapy.layers.dot15d4
except:
    print "Scapy-com required to use scapy-extensions.py"
    print "Scapy-com can be found at http://bb.secdev.org/scapy-com"
    sys.exit()
=======================================

What is the expected output? What do you see instead?

Packets should parse properly without error.

What version of the product are you using?

KillerBee beta (from SVN checkout) Revision # 93

On what operating system?

Linux kubuntu_rules 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 
2014 x86_64 x86_64 x86_64 GNU/Linux

With what Python version? (python -V)

Python 2.7.5+

Is scapy-com installed?

No, not on this system

Please provide any additional information below.


```

Original issue reported on code.google.com by `cutaways...@gmail.com` on 16 Sep 2014 at 10:37

**Comment by EastL** [comment]
I have the same problem and I installed scapy-com..

>>> kbrdpcap("11_002.pcap")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/killerbee/scapy_extensions.py", line 234, in kbrdpcap
    else:     packet = Dot15d4FCS(packet[1])
NameError: global name 'Dot15d4FCS' is not defined

**Comment by joswr1ght** [comment]
I think perhaps you don't have scapy-com installed, or you are loading the official Scapy build instead of Scapy-com.  I just installed Scapy-com and KillerBee just fine on Kali 1.0.7:

```
# hg clone https://bitbucket.org/secdev/scapy-com
# cd scapy-com/
# python setup.py install
# cd ..
# apt-get install python-gtk2 python-cairo python-usb python-crypto python-serial python-dev libgcrypt-dev
# git clone https://github.com/riverloopsec/killerbee.git
# cd killerbee/killerbee
# python setup.py install
# zbscapy
WARNING: No route found for IPv6 destination :: (no default route?)
Welcome to Scapy (2.2.0-dev)
KillerBee Extension v0.6
>>> p=kbrdpcap("sample/control4-sample.pcap")
WARNING: FCS on this packet is invalid or is not present in provided bytes.
WARNING: FCS on this packet is invalid or is not present in provided bytes.
WARNING: more FCS on this packet is invalid or is not present in provided bytes.
>>> p[0]
<Dot15d4FCS  fcf_reserved_1=0 fcf_panidcompress=True fcf_ackreq=False fcf_pending=False fcf_security=False fcf_frametype=Data fcf_srcaddrmode=Short fcf_framever=0 fcf_destaddrmode=Short fcf_reserved_2=0 seqnum=14 |<Dot15d4Data  dest_panid=0x3359 dest_addr=0xffff src_addr=0x0 |<ZigbeeNWK  discover_route=0 proto_version=2 frametype=command flags=security+extended_src destination=0xfffc source=0x00 radius=1 seqnum=192 ext_src=0f:ff:00:00:1f:02:22 |<ZigbeeSecurityHeader  reserved1= extended_nonce=1 key_type=network_key nwk_seclevel=None fc=0x0122ba source=0f:ff:00:00:1f:02:22 key_seqnum=0 data='e\x8d\xf3{j\xf6\x97m\xa6' |>>>>
```

Maybe try removing Scapy from your system and use these steps to install Scapy-com and try again?

-Josh

**Comment by EastL** [comment]
I installed scapy-com by your step, but I got the same error......
My OS is ubuntu, how can I know the scapy-com is installed sucessfully?

**Comment by EastL** [comment]
/usr/local/lib/python2.7/dist-packages/scapy/layers$ ls
all.py         dot15d4.py    ir.py       mgcp.py       pflog.py        rtp.py         ssl.py
all.pyc        dot15d4.pyc   ir.pyc      mgcp.pyc      pflog.pyc       rtp.pyc        ssl.pyc
bluetooth.py   eigrp.py      isakmp.py   mobileip.py   ppi_cace.py     sctp.py        tftp.py
bluetooth.pyc  eigrp.pyc     isakmp.pyc  mobileip.pyc  ppi_cace.pyc    sctp.pyc       tftp.pyc
cdp.py         gprs.py       l2.py       ms.py         ppi_geotag.py   sebek.py       vrrp.py
cdp.pyc        gprs.pyc      l2.pyc      ms.pyc        ppi_geotag.pyc  sebek.pyc      vrrp.pyc
dhcp6.py       hsrp.py       l2tp.py     netbios.py    ppi.py          sixlowpan.py   x509.py
dhcp6.pyc      hsrp.pyc      l2tp.pyc    netbios.pyc   ppi.pyc         sixlowpan.pyc  x509.pyc
dhcp.py        inet6.py      lldp.py     netflow.py    ppp.py          skinny.py
dhcp.pyc       inet6.pyc     lldp.pyc    netflow.pyc   ppp.pyc         skinny.pyc
dns.py         inet.py       llmnr.py    ntp.py        radius.py       smb.py
dns.pyc        inet.pyc      llmnr.pyc   ntp.pyc       radius.pyc      smb.pyc
dot11.py       __init__.py   loop.py     ospf.py       rip.py          snmp.py
dot11.pyc      __init__.pyc  loop.pyc    ospf.pyc      rip.pyc         snmp.pyc


It looks like installed sucessful and dot15d4.pyc is exist..... but I still failed... Whyyyyy...
~/Devlopment/killerbee$ zbscapy 
WARNING: No route found for IPv6 destination :: (no default route?)
WARNING: Most KillerBee functionality requires root privileges.
Welcome to Scapy (2.2.0)
KillerBee Extension v0.6
>>> p=kbrdpcap("sample/control4-sample.pcap")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/killerbee/scapy_extensions.py", line 234, in kbrdpcap
    else:     packet = Dot15d4FCS(packet[1])
NameError: global name 'Dot15d4FCS' is not defined

**Comment by riverloopsec** [comment]
Yes, @joswr1ght's listing above also works in our testing. The only thing I can think of is if you had two Python installs and one is using a different package directory than where scapy-com installed?
I have added the branch bugfix/27-scapycom-detect to address the original concern of detecting and alerting the user. Please provide testing of this branch to let us know if it is useful and should be merged.

**Comment by taylorcenters** [comment]
closed - long idle
