### ISSUE TITLE
zbreplay includes FCS (using RZUSBStick)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [riverloopsec/killerbee#32]
```
What steps will reproduce the problem?
1. Apply zbreplay

What is the expected output? What do you see instead?
The firmware of the RZUSBStick adds an additional FCS field despite the fact 
that a pcap file already includes the FCS field. Therefore the injected packet 
has two FCS fields

What version of the product are you using?
[ ] KillerBee 1.0 (from TAR file)
[X] KillerBee beta (from SVN checkout) Revision # 99
[ ] Other:

On what operating system?
Ubuntu 14.04

With what Python version? (python -V)
2.7.6

Is scapy-com installed?
yes

Please provide any additional information below.
The last two bytes (FCS) of packets read by PcapReader should be removed before 
the packets will be injected.


```

Original issue reported on code.google.com by `Norman.G...@googlemail.com` on 6 Mar 2015 at 12:37

**Comment by joswr1ght** [comment]
I think PcapReader() *should* return the entire packet, including FCS. Indeed, how else could we return the FCS to the caller?  If you are replaying packets, then you should replay packet[0:-2] to omit the FCS in the retransmitted frame.  That's the caller's responsibility.

Closing this issue, but if you feel strongly about it and want to suggest an alternate solution, please re-open this ticket.

-Josh

**Comment by joswr1ght** [comment]
My bad, I fixed this issue in zbreplay ```kb.inject(packet[0:-2])```, thanks to Chris Duca for working through this with me.
