### ISSUE TITLE
Changes to PyUSB remove parameters from some calls

### ISSUE THREAD

**Issue by cybergibbons** [riverloopsec/killerbee#37]
Later versions of PyUSB (1.0.0rc1 installed using pip) have removed some unecessary length parameters from some calls:
https://github.com/walac/pyusb/commit/dac78933f6a6eaf5ae82f48e2f4e7d1733dc2f98

Calls to these functions need altering to work.

**Comment by riverloopsec** [comment]
Thanks for the note. If you look in killerbee/dev_rzusbstick.py we're still doing pyUSB0 vs pyUSB1 support -- but this change looks like it may be tougher as there isn't a clean way to tell which version people are using. It looks like a few places need to be changed if the get_string call in that commit is really the only update:
```
killerbee/dev_rzusbstick.py:                    usb.util.get_string(self.dev, 50, self.dev.iProduct),     \
killerbee/dev_rzusbstick.py:                    usb.util.get_string(self.dev, 50, self.dev.iSerialNumber) ]
killerbee/kbutils.py:                            usb.util.get_string(dev, 50, dev.iProduct),     \
killerbee/kbutils.py:                            usb.util.get_string(dev, 50, dev.iSerialNumber)])
```
