### ISSUE TITLE
zbdump memory corruption 

### ISSUE THREAD

**Issue by ridingintraffic** [riverloopsec/killerbee#39]
i have been receiving this error a lot today.   is it a flaw in the firmware i built or a software issue?

zbdump: listening on '001:005', link-type DLT_IEEE802_15_4, capture size 127 bytes
*** glibc detected *** /usr/bin/python: malloc(): memory corruption: 0x010a29b0 ***

**Comment by riverloopsec** [comment]
It looks like your python process itself has memory corruption... which seems very odd. Did you recently upgrade to a new python program? Do you get it when running other tools that capture data, like zbwireshark? What about when sending frames (zbreplay)? What about on non KillerBee python programs?

**Comment by rmspeers** [comment]
Closing but let me know if we need to reopen.
