### ISSUE TITLE
Find network key using ZBDSNIFF

### ISSUE THREAD

**Issue by Auron691** [riverloopsec/killerbee#79]
Hi all, i create a ZigBee network using Xbee series 2 model xb24-z7wit-004.
I have sniff a lot of packets using AVRUSBSTICK with default firmware and save that in a .dump file.
After that i have converter this into dcf using zbconvert, but when i try to find network key using Zbdsniff, it process 2 files (.dump and .dcf) but it don't find any network key. I am sure that the communication is encrypt.

I attached .dump file if someone would test it.
[Enc.zip](https://github.com/riverloopsec/killerbee/files/606949/Enc.zip)

Thanks for support

**Comment by Sandb0xED** [comment]
Hi, I'm trying to use zbdsniff to extract the network key from a pcap (captured from zbdump). However, I keep getting an AttributeError: 'NoneType' object has no attribute 'source'.  Do you have any ideas on how I debug?

![image](https://user-images.githubusercontent.com/49734738/83312417-33154680-a1e0-11ea-9215-20f95d6658fe.png)

**Comment by taylorcenters** [comment]
hi, can you try on the python3 version and update the output?

**Comment by taylorcenters** [comment]
Closing as inactive. Please create a new issue if you experience this problem with the current version!
