### ISSUE TITLE
ERROR: No module named AESCCMDot15d4

### ISSUE THREAD

**Issue by iotfu** [riverloopsec/killerbee#81]
Hi there!

Whenever I import anything killerbee related I get this Error.
I think this also affects the packets I send in some form and so far I could'nt find a solution online.
What should I do?

Thanks in advance.

**Comment by rmspeers** [comment]
It looks like you likely don’t have the right version of Scapy-com installed. Where did you install that from?

**Comment by rmspeers** [comment]
@iotfu - I wanted to follow up on this and confirm if you were able to resolve.

**Comment by rmspeers** [comment]
Closing due to no active discussion.
