### ISSUE TITLE
Incoming USB packets truncated to 64 bytes with RZ USB Stick

### ISSUE THREAD

**Issue by Scytmo** [riverloopsec/killerbee#87]
USB Air Capture packets are truncated to 64 bytes for the RZ USB Stick.
This results in sniffing tools (such as zbwireshark) returning truncated packets.
This appears to be due to bMaxPacketSize0 being 64, resulting in the USB firmware sending multiple USB packets, but the driver (dev_rzusbstick.py) not re-building packets received in multiple segments (in 'pnext').

**Comment by rmspeers** [comment]
Resolved by @Scytmo 's PR.
