### ISSUE TITLE
When can i expect full killerbee support for other zigbee dongles?

### ISSUE THREAD

**Issue by ankitamarwah** [riverloopsec/killerbee#95]
I am using RZUSB stick, and I am trying to get one extra and i couldn't find it stock anywhere. 
Just want to check if there is any other USB dongle which supports both sniffing and replay of packets? 
Other than telosb mote and apimote.

**Comment by rmspeers** [comment]
Support for the CC2531/CC2530 dongles is now merged. I will update help text soon.
