### ISSUE TITLE
Issues with zbfind

### ISSUE THREAD

**Issue by sgript** [riverloopsec/killerbee#97]
I've come across this issue where when using zbfind nothing actually happens. As I have seen this mentioned somewhere else also, I was wondering what the issue was (if it's known) and if it's possible for me to get it to work?

![screenshot from 2017-07-03 19-21-04](https://user-images.githubusercontent.com/7774083/27804503-2596b9c4-6027-11e7-96fd-1bb822c97a4c.png)

So I just get the following error:

```
sudo python zbfind
Warning: You are using pyUSB 1.x, support is in beta.
Error initializing KillerBee Sniffer

```

**Comment by rmspeers** [comment]
Please try out zbid and zbwireshark, and then zbstumbler. Run them all as sudo given that is how you are running zbfind. It looks like your computer isn't able to connect to a KillerBee device correctly.

**Comment by sgript** [comment]
Is there any way I can fix that? I am currently using Ubuntu 16.04 natively installed on a HP Pavilion dv6. Issue is with

**Comment by rmspeers** [comment]
@sgript have you tried out zbid, zbwireshark, and zbstumbler? What are those doing for you? I want to see if those are detecting and properly connecting to your device.

**Comment by sgript** [comment]
@rmspeers I had issues getting hold of the TelosB Mote from Advanticsys, so I'm using an RZ Raven USB, flashed. All three of the tools you mentioned are working.
